# Generated by Django 4.2.4 on 2024-09-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_fac', models.CharField(max_length=100)),
                ('group_kaf', models.CharField(max_length=100)),
                ('group_course', models.PositiveIntegerField()),
                ('group_count', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('audience', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_screen.group')),
            ],
        ),
    ]
