# Generated by Django 4.2.4 on 2024-10-31 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='ГЗ', max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='черновик', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LessonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('audience', models.CharField(max_length=100)),
                ('headboy', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ordergroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ordergroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ordergroup',
            name='order',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_fac',
            new_name='facultet',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='contact',
            new_name='headboy',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_kaf',
            new_name='kafedra',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderGroup',
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_screen.group'),
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_screen.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='groups',
            field=models.ManyToManyField(through='main_screen.LessonGroup', to='main_screen.group'),
        ),
        migrations.AlterUniqueTogether(
            name='lessongroup',
            unique_together={('lesson', 'group')},
        ),
    ]
