# Generated by Django 4.2.4 on 2024-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0003_alter_lesson_date_alter_lesson_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='groups',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=30),
        ),
    ]
