# Generated by Django 4.2.4 on 2024-11-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0004_remove_lesson_groups_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.CharField(default='12:00', max_length=30),
        ),
    ]
