# Generated by Django 4.2.4 on 2024-11-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0005_alter_lesson_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='РИП', max_length=100),
        ),
    ]
