# Generated by Django 4.2.4 on 2024-11-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0006_lesson_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lessongroup',
            table='Lesson_in_progress',
        ),
    ]
