# Generated by Django 4.2.4 on 2024-11-13 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0008_lesson_completion_datetime_lesson_creation_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
