# Generated by Django 4.2.4 on 2024-12-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0009_alter_lesson_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessongroup',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='lessongroup',
            name='building',
        ),
        migrations.AddField(
            model_name='lesson',
            name='audience',
            field=models.CharField(default='209', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='building',
            field=models.CharField(default='ГЗ', max_length=100),
        ),
    ]
