# Generated by Django 4.2.4 on 2025-02-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0011_lesson_lecturer_lesson_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
