# Generated by Django 4.2.4 on 2025-02-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0012_lesson_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_active',
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
